### PR TITLE
Fixed search mapping for EL 7+

### LINKED ISSUE #105: Incompatibility of  Full text search - Elasticsearch Platform 1.5.1 with Elasticsearch version 7.7.0
sudo -u www-data php /var/www/nextcloud/occ fulltextsearch:test stops wit following exception:
 - 'test' An unhandled exception has been thrown:
TypeError: Return value of OCA\FullTextSearch\Model\SearchRequest::getProviders() must be of the type array, null returned in /var/www/nextcloud/apps/fulltextsearch/lib/Model/SearchRequest.php:114
Stack trace:
#0 /var/www/nextcloud/apps/fulltextsearch/lib/Model/SearchRequest.php(700): OCA\FullTextSearch\Model\SearchRequest->getProviders()
#1 [internal function]: OCA\FullTextSearch\Model\SearchRequest->jsonSerialize()
#2 /var/www/nextcloud/apps/fulltextsearch_elasticsearch/lib/Service/SearchService.php(103): json_encode(Object(OCA\FullTextSearch\Model\SearchRequest))
#3 /var/www/nextcloud/apps/fulltextsearch_elasticsearch/lib/Platform/ElasticSearchPlatform.php(336): OCA\FullTextSearch_ElasticSearch\Service\SearchService->searchRequest(Object(Elasticsearch\Client), Object(OCA\FullTextSearch\Model\SearchResult), Object(OC\FullTextSearch\Model\DocumentAccess))
#4 /var/www/nextcloud/apps/fulltextsearch/lib/Command/Test.php(584): OCA\FullTextSearch_ElasticSearch\Platform\ElasticSearchPlatform->searchRequest(Object(OCA\FullTextSearch\Model\SearchResult), Object(OC\FullTextSearch\Model\DocumentAccess))
#5 /var/www/nextcloud/apps/fulltextsearch/lib/Command/Test.php(436): OCA\FullTextSearch\Command\Test->search(Object(Symfony\Component\Console\Output\ConsoleOutput), Object(OCA\FullTextSearch_ElasticSearch\Platform\ElasticSearchPlatform), Object(OCA\FullTextSearch\Provider\TestProvider), Object(OC\FullTextSearch\Model\DocumentAccess), 'test', Array)
#6 /var/www/nextcloud/apps/fulltextsearch/lib/Command/Test.php(171): OCA\FullTextSearch\Command\Test->testSearchSimple(Object(Symfony\Component\Console\Output\ConsoleOutput), Object(OCA\FullTextSearch_ElasticSearch\Platform\ElasticSearchPlatform), Object(OCA\FullTextSearch\Provider\TestProvider))
#7 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\FullTextSearch\Command\Test->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/nextcloud/core/Command/Base.php(168): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/nextcloud/3rdparty/symfony/console/Application.php(915): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/nextcloud/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(OCA\FullTextSearch\Command\Test), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/nextcloud/lib/private/Console/Application.php(214): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/nextcloud/console.php(99): OC\Console\Application->run()
#14 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')

### PR DESCRIPTION
**Pull request by weberhofer**
Fixes #105 and #106. Should be compatible with older versions, too.

Signed-off-by: Johannes Weberhofer <jweberhofer@weberhofer.at>

### CODE REVIEW

**Comment by Happyfeet01** [comment]
One review please

**Comment by snapet** [comment]
Would be nice if this manages to get approved and available as an app update as there are quite a few issues on the forum that come down to having this change applied.

**Comment by hashworks** [comment]
Just a thought: Wouldn't this also break EL <= 6?

**Comment by davidcheeeese** [comment]
Seems not working for everybody #105

**Comment by conradp24** [comment]
> Seems not working for everybody #105

Glad I found this, its been killing me over the last few days trying to resolve this.
I've got exactly the same issue, despite applying the changes. I switched from Elasticsearch docker to elk to try and resolve as the supporting documentation is better (have no prior experience with ElasticSearch), but the issues led me here.

**Comment by wmader** [comment]
Reading the conversation, I get the impression that the issues is solved. What is it that prevents merging this PR? Is there anything I as a user can help with?

**Comment by micky1067** [comment]
I have a short question. Where and what I must change ?
I can not find a file named SearchMappingService.php
Where I can find it ? I use Ubuntu 18.04 for elasticsearch and nextcloud

**Comment by earlng** [comment]
Just wanted to say that this solved my problem as well.

**Comment by enoch85** [comment]
ping @daita Please merge.

**Comment by enoch85** [comment]
FYI @Ark74

**Comment by enoch85** [comment]
This patch is now used in the Nextcloud VM: https://github.com/nextcloud/vm/blob/master/apps/fulltextsearch.sh#L168-L170

**Comment by daita** [comment]
Can you rebase and confirm that this is working on master with ES 7.8 ? 

I cannot pass the `./occ full:test`.

**Comment by thomasgg23** [comment]
> Can you rebase and confirm that this is working on master with ES 7.8 ?
> 
> I cannot pass the `./occ full:test`.

You are right, me neither.

sudo -u www-data php occ full:test

.Testing your current setup:
Creating mocked content provider. ok
Testing mocked provider: get indexable documents. (2 items) ok
Loading search platform. (Elasticsearch) ok
Testing search platform. ok
Locking process ok
Removing test. ok
Pausing 3 seconds 1 2 3 ok
Initializing index mapping. ok
Indexing generated documents. ok
Pausing 3 seconds 1 2 3 ok
Retreiving content from a big index (license). (size: 32386) ok
Comparing document with source. ok
Searching basic keywords:
 - 'test' (result: 1, expected: ["simple"]) ok
 - 'document is a simple test' (result: 0, expected: ["simple","license"]) fail
Error detected, unlocking process ok
In Test.php line 652:

  Unexpected SearchResult: {"provider":{"id":"test_provider","name":"Test Provider"},"platform":{"id":"elastic_search","name":"Elasticsearch"},"documents":[],"info":[],"meta":{"
  timedOut":false,"time":7,"count":0,"total":0,"maxScore":0}}


fulltextsearch:test [--output [OUTPUT]] [-j|--json] [-d|--platform_delay PLATFORM_DELAY]

Specs:
- elasticsearch 7.8.0
- apache 2.4.29
- php 7.2.24
- nextcloud 19.0.1

The fulltextsearch within nextcloud is working without a problem anyway.

**Comment by daita** [comment]
> The fulltextsearch within nextcloud is working without a problem anyway.

Yes it should be ok but only for simple request. As an example, forcing (+) or filtering terms (-) are not working anymore.
However, I don't think there is any security/privacy issue.

I will see how to fix the mapping

**Comment by thomasgg23** [comment]
> Yes it should be ok but only for simple request. As an example, forcing (+) or filtering terms (-) are not working anymore.

You are right, these are not working.
We are only using simple search terms.

**Comment by daita** [comment]
This one should be better: https://github.com/nextcloud/fulltextsearch_elasticsearch/pull/114

**Comment by daita** [comment]
Thanks for your time on this PR, i will however close it as mine was a little less buggy :]

**Pull request closed without merging**
