### PR TITLE
Add support for searching in external files (fixing #89)

### LINKED ISSUE #89: Full Text Search Finds No Results For External Storage
Duplicate of nextcloud/fulltextsearch#546 but I think it's related to this repository.

We are investigating a problem with searching on external storages. 
I think there is a problem with the owner / group rights on external storage files. In my case there are no meta-informations in the file about a owner (owner tag is empty). So I worked around and added the following to https://github.com/nextcloud/fulltextsearch_elasticsearch/blob/7dad22ec36df258eaeb2759080ebce3d1857206d/lib/Service/SearchMappingService.php#L318-334

```php
private function generateSearchQueryAccess(IDocumentAccess $access): array {
	$query = [];
	$query[] = ['term' => ['owner' => $access->getViewerId()]];
	// add this:
	$query[] = ['term' => ['owner' => '']]; // Files on external storages didn't have owner information
	$query[] = ['term' => ['users' => $access->getViewerId()]];
	$query[] = ['term' => ['users' => '__all']];
	foreach ($access->getGroups() as $group) {
		$query[] = ['term' => ['groups' => $group]];
	}
	foreach ($access->getCircles() as $circle) {
		$query[] = ['term' => ['circles' => $circle]];
	}
	return $query;
}
```
So the search request returns files with no owner information too. But I think this can be security problem. In my case the solution works.

All futher information are collected in the issue nextcloud/fulltextsearch#546.

### PR DESCRIPTION
**Pull request by R0Wi**
This fixes #89. It is implemented like proposed here: https://github.com/nextcloud/fulltextsearch/issues/546#issuecomment-583791976

### CODE REVIEW

**Comment by 4ipalino** [comment]
Are there plans when this PR will be considered and released?

**Comment by R0Wi** [comment]
@4ipalino does this fix the issue for you?

**Comment by 4ipalino** [comment]
@R0Wi I tested it again and it worked on my system. As long as the external Drive is not used as Rootdirectory with foldername "/". 

It´s important to set an explicit foldername for the external share:
image

**Comment by R0Wi** [comment]
Thanks for the feedback. Thats a case i didn't test so i'll have a look at this. Maybe i can implement a solution for that, too.

**Comment by R0Wi** [comment]
@4ipalino i modified the patch so now a external share mounted as root-directory should also work. If that's the case, the check of the filepath is now omitted because logically seen every "external file" is allowed to appear in the search result. 

Maybe you would like to check that out if you've some time left and give me feedback on this :smile:

**Comment by trendzetter** [comment]
I can confirm the fix is working. The code looks fine but probably my opinion is is not enough as a review since I am  not a nextcloud developer.

**Comment by skjnldsv** [comment]
> @daita @MorrisJobke or maybe @skjnldsv any chance to get some feedback on this, please?

Sorry, this is out of my expertise! :/

**Comment by trendzetter** [comment]
WTF!? This is a fix for a major blocking bug in one of the most important features to make this enterprise ready. Why is no-one of the core team willing to review your code?? Seems like they need the bugs to sell more support contracts or what??

**Comment by daita** [comment]
Hello, main dev on fts here.

I was supposed to work on the app last week but got overwhelmed by other more important thing.

**Comment by R0Wi** [comment]
> Hello, main dev on fts here.
> 
> I was supposed to work on the app last week but got overwhelmed by other more important thing.

No problem for me. I already did a few minor improvements for some customers who use the FTS so maybe it would be interesting for you if i can support you somehow. Just let me know :-)

**Comment by trendzetter** [comment]
Sorry for my emotional reaction. I am looking into the contribution guidelines, see if I can make more of a contribution instead of pointing out issues.

**Comment by trendzetter** [comment]
I am still figuring out why this happens, not sure if it has anything to do with this fix but I am not seeing all of the results found. I often see only one or 2 or even no results listed. I just know results are found because it displays on top of the page:"de zoekopdracht in Files naar 'bunny' leverde 8 resultaten op in 51 ms"  (8 results found in Dutch)

**Comment by R0Wi** [comment]
> I am still figuring out why this happens, not sure if it has anything to do with this fix but I am not seeing all of the results found. I often see only one or 2 or even no results listed. I just know results are found because it displays on top of the page:"de zoekopdracht in Files naar 'bunny' leverde 8 resultaten op in 51 ms" (8 results found in Dutch)

I think this has nothing to do with this change i should rather be a frontend problem (this fix just extends the backend search mechanism). Maybe you could take a look at the dev-console network tab and see the JSON response returned by the server? If the result rows are missing it could be something on the backend otherwise i'd say there's something going on in the frontend javascript code or something. If you like you can create a issue [here](https://github.com/R0Wi/fulltextsearch_elasticsearch/issues) and i'll see if i can help you somehow (just to keep this discussion clean here)

**Comment by Jake-Etherflow** [comment]
Works perfectly! Thank you very much. I was able to mount nfs and then map nextcloud local storage to it with no further issues displaying results for the index.

**Comment by daita** [comment]
Hello,

There is no reason for this app to search/access remote files. Can you try to migrate your work onto files_fulltextsearch ?

**Comment by R0Wi** [comment]
Well currently the issue is that external files are properly indexed (with the help of `files_fulltextsearch`). But the results (indexed files) are then filtered by ownership when creating a search request inside this app. Because external files do not have a special owner they're filtered. 

My current approach is to get all external mounts accessible to the current user when he uses the search functionallity. This info can then be integrated into the filter part of the ES query.

I know that this somehow mixes up the separation between `files_fulltextsearch` and `fulltextsearch_elasticsearch` but i did not find another way to implement the mentioned feature. Maybe you could give a draft on how to provide this inside `files_fulltextsearch`? I'd then really be looking forward implementing this :-)

**Comment by omidmeh** [comment]
I'm also very interested in this. 

In the meantime, I tried just downloading the files that you've changed and replacing the ones from the original plugin installation with them. However, it looks like when I do that the search no longer works!

Is there any other steps I need to take other than replacing the old files with these in the installation folder?

**Comment by Jake-Etherflow** [comment]
I don't remember where the other patch was, but I had to combine the two in the same file to get search working and external files as well. If you'd like a copy of it, shoot me a message, and I can send it to you.

**Comment by R0Wi** [comment]
@omidmeh i think what you could do is cloning this repo, applying the patch from this PR and installing the apps dependencies manually (note you need to install [git](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git) as well as [composer](https://getcomposer.org/doc/00-intro.md#installation-linux-unix-macos)). So basically you could do something like this:
```bash
cd <NEXTCLOUD_ROOT>/apps
rm -rf fulltextsearch_elasticsearch
mkdir fulltextsearch_elasticsearch && cd fulltextsearch_elasticsearch
git clone https://github.com/nextcloud/fulltextsearch_elasticsearch.git .
curl https://patch-diff.githubusercontent.com/raw/nextcloud/fulltextsearch_elasticsearch/pull/100.patch | git apply -v
composer install
cd .. && chown -R www-data:www-data fulltextsearch_elasticsearch
```

Let me know if this helps.

**Comment by omidmeh** [comment]
This fixed my issue as well. Thank you!!

**Comment by omidmeh** [comment]
The only thing that I noticed is that when I search for something that belongs to a different user, although I don't actually see the result, it does show "the search in Files for 'search-term' returned 1 results in 56 ms". 

That's still a huge improvement since the owner user sees the file but the non-owners don't. Would be nice if we could adjust that number as well though!

**Comment by R0Wi** [comment]
Could be related to https://github.com/R0Wi/fulltextsearch_elasticsearch/issues/1

**Comment by ravermeister** [comment]
sigh, I really hope this fix find the way to the master branch (and the next Version). otherwise the whole thing is nearly useless, even worse, It gives the User the wrong feeling about the content of his own data!.

**Comment by lhurt** [comment]
Why is it not merged to the main branch?

**Comment by Apfelwurm** [comment]
Hi, can please someone of the staff review this PR? It works perfectly and its a pain to implement this fix for every release manually.
Thanks!

**Comment by trendzetter** [comment]
I think someone is waiting for your good consultancy fees.

**Comment by R0Wi** [comment]
Like mentioned in https://github.com/nextcloud/fulltextsearch_elasticsearch/pull/100#issuecomment-668095902 this PR does not respect the separation of concerns between the FTS apps (even it works...). Unfortunately currently i don't have much time to port my work onto `files_fulltextsearch`  because i think this would be a bit more heavy lifting.

**Comment by tauceti82** [comment]
> @omidmeh i think what you could do is cloning this repo, applying the patch from this PR and installing the apps dependencies manually (note you need to install [git](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git) as well as [composer](https://getcomposer.org/doc/00-intro.md#installation-linux-unix-macos)). So basically you could do something like this:
> 
> ```shell
> cd <NEXTCLOUD_ROOT>/apps
> rm -rf fulltextsearch_elasticsearch
> mkdir fulltextsearch_elasticsearch && cd fulltextsearch_elasticsearch
> git clone https://github.com/nextcloud/fulltextsearch_elasticsearch.git .
> git checkout v1.5.2
> curl https://patch-diff.githubusercontent.com/raw/nextcloud/fulltextsearch_elasticsearch/pull/100.patch | git apply -v
> composer install
> cd .. && chown -R www-data:www-data fulltextsearch_elasticsearch
> ```
> 
> Let me know if this helps.
> 
> EDIT: note that v1.5.2 should already contain the fix regarding ES7.7 support mentioned by @Jake-Etherflow so the above should work

the 100.patch was adapted so it couldn't patch the Makefile as the version+=1.5.2 was changed to 20.0.0 so it could not find the correct positions to patch...what helped was to manually change version+=1.5.2 to version+=20.0.0 before applying the patch... 

And then do in the end occ upgrade otherwise it will disable the plugin.

it cost me hours to get the search working on external files! This has to be fixed asap!

**Comment by R0Wi** [comment]
@tauceti82 sorry for the circumstances i rebased this PR onto the current `v21.0.0` so you should now be able to apply the patch again by `git checkout v21.0.0` and then following the commands from above. Maybe i manage to build a regularly updated custom .tar file via Github Actions and link it here these days.

**Comment by Apfelwurm** [comment]
Any chance this problem can get revisited?

**Comment by R0Wi** [comment]
ping @ArtificialOwl

**Comment by trendzetter** [comment]
@adsworth  ?

**Comment by ArtificialOwl** [comment]
it is possible that https://github.com/nextcloud/files_fulltextsearch/pull/170 fixes this issue. this needs confirmation

**Comment by R0Wi** [comment]
@ArtificialOwl thank's but if i understand the code correctly, this most likely doesn't solve the problem for external files. It's already a long time ago i dealt with the code but if i remember correctly, the main problem was the search filter condition in https://github.com/nextcloud/fulltextsearch_elasticsearch/pull/100/files#diff-b55ac6e506ccacc79909f6e0bb3d312f92a4d33e089c0d952fe032fdfe60fb71R378 which currently does not allow search results to have an empty owner when searching inside the index.

Nevertheless i'm going to test the patch these days and give you some feedback on this 👍

**Comment by lhurt** [comment]
> @ArtificialOwl thank's but if i understand the code correctly, this most likely doesn't solve the problem for external files. It's already a long time ago i dealt with the code but if i remember correctly, the main problem was the search filter condition in https://github.com/nextcloud/fulltextsearch_elasticsearch/pull/100/files#diff-b55ac6e506ccacc79909f6e0bb3d312f92a4d33e089c0d952fe032fdfe60fb71R378 which currently does not allow search results to have an empty owner when searching inside the index.
> 
> Nevertheless i'm going to test the patch these days and give you some feedback on this 👍

Hi, is there any noteworthy progress on this issue?

**Comment by trendzetter** [comment]
> Hi, is there any noteworthy progress on this issue?
It looks promising and it's merged. I haven't tested myself but I suppose the best thing to do is try install a vanilla build and see if searching works now on external files

**Comment by trendzetter** [comment]
I managed to test this scenario again and I can confirm searching using the search box works for external files now.
Unless someone else thinks this needs to be reopened I think it's probably OK to close.

**Comment by R0Wi** [comment]
Also tested it on a fresh NC25 instance with one and two users and a samba share. Seems to work now because there was a change how files are indexed. Don't know when this changes came into the app but with app version 24 searching in external files seems to be fixed. Thank's @ArtificialOwl or who else fixed this :+1:

**Comment by lhurt** [comment]
Unfortunately it doesn't work for me.

I have some Samba shares, where each user has to provide its password in the configuration.

My test included the following steps

1. Recreate index for all users from scratch
2. Show live indexing (occ fulltextsearch:live)
3. Copy a file on an indexed directory using linux bash
4. Copy a file via Windows Explorer in the very same directory
5. No indexing is displayed in the live search
6. All previously existing files can be found using nextcloud search, but not the copied ones

Any idea what could be wrong?

**Comment by R0Wi** [comment]
@lhurt since the fulltextsearch app heavy relies on the [file-system events of NC](https://docs.nextcloud.com/server/latest/developer_manual/basics/events.html#filesystem-root) (like for example when a new file is detected by Nextcloud), I think you're hitting the problem, that files which are directly added to the samba share do not trigger the NC events. See [official docs](https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/external_storage/smb.html#smb-update-notifications). If indexing works when uploading the file directly to NC (for example via WebUI), then this is most likely not a problem with the fulltextsearch app itself.

**Comment by lhurt** [comment]
> 

Thanks for the explanation. Wouldn't [https://www.php.net/manual/en/book.inotify.php](https://www.php.net/manual/en/book.inotify.php) help to improve the situation. I'm not sure if this is the correct place to ask. Please forgive me if I'm completely off track. I've no PHP development skills.

**Pull request closed without merging**
