### PR TITLE
Parse elastic error response

### PR DESCRIPTION
**Pull request by kesselb**
to show a more detailed error message why the indexing failed.

Screenshot from 2021-06-10 16-06-09

for example if a password protected file is uploaded. Somehow the first caused_by is more "meaningful" then the second one because Cannot decrypt PDF; the password is incorrect is a bit misleading as we don't provide a password at all. We could just check if there is a caused_by and use the first one and don't dive into the structure. I don't have a strong opinion - whatever you prefer ;)

https://www.encryptomatic.com/pdfpostman/open-encrypted-pdf.html for a pdf file with password protection.

### CODE REVIEW

**Review by R0Wi — APPROVED** [review]
LGTM :sunglasses:

**Comment by CSchmidtDD** [comment]
Can we get a second review here to merge it for our current production issue? @MorrisJobke @Ark74

**Review by MorrisJobke — APPROVED** [review]
🐘

**Pull request merged**
